### ISSUE TITLE
Regular Labs Modules question

### ISSUE THREAD

**Issue by dmitriitux** [renekreijveld/YOOthemeMegaMenu#2]
hi, why do you need Regular Labs Modules? It is not necessary, joomla already has processing, {loadmoduleid} and {loadposition}. An unnecessary extension, it inflates the processing, unnecessary consumption of resources and, accordingly, the return of the page by the server.

**Comment by renekreijveld** [comment]
According to the Regular Labs developer the default loadposition plugin cannot be used inside modules, see here: https://regularlabs.com/modulesanywhere.
But I will rewrite the view code so I don't need the modules anywhere plugin or the loadposition plugin.

**Comment by renekreijveld** [comment]
Code is rewritten so it no longer needs the Modules Anywhere plugin or the Load Modules plugin.
