### ISSUE TITLE
Some mistake

### ISSUE THREAD

**Issue by elfest1** [renekreijveld/YOOthemeMegaMenu#3]
Good afternoon.
After installing and publishing the module, an error is displayed...

[Link on screenshot](https://disk.yandex.ru/i/yGv8b3S2-5fjCw)

P.S. Joomla has just been installed on a local server (I also tried it on a working hosting, the same thing)

**Comment by renekreijveld** [comment]
That is not an error but a warning. You can hide it for now by setting Error reporting to none in the Joomla Global Configuration. I will try to solve the warning.

**Comment by elfest1** [comment]
Thanks for the reply. Disabled warnings in the global configuration. But, by default, it is enabled, and most users will also have this problem...

**Comment by renekreijveld** [comment]
The warning message is fixed now. Please download and install version 1.0.2.
